// Code generated by protoc-gen-go. DO NOT EDIT.
// source: routed_msg.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LineCrossing_Direction int32

const (
	LineCrossing_Undefined LineCrossing_Direction = 0
	LineCrossing_NB        LineCrossing_Direction = 1
	LineCrossing_EB        LineCrossing_Direction = 2
	LineCrossing_SB        LineCrossing_Direction = 3
	LineCrossing_WB        LineCrossing_Direction = 4
)

var LineCrossing_Direction_name = map[int32]string{
	0: "Undefined",
	1: "NB",
	2: "EB",
	3: "SB",
	4: "WB",
}

var LineCrossing_Direction_value = map[string]int32{
	"Undefined": 0,
	"NB":        1,
	"EB":        2,
	"SB":        3,
	"WB":        4,
}

func (x LineCrossing_Direction) String() string {
	return proto.EnumName(LineCrossing_Direction_name, int32(x))
}

func (LineCrossing_Direction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5813568a872f642d, []int{4, 0}
}

type Position struct {
	Latitude             int32    `protobuf:"varint,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            int32    `protobuf:"varint,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_5813568a872f642d, []int{0}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetLatitude() int32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Position) GetLongitude() int32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type RoutedMsg struct {
	MsgBytes                   []byte                 `protobuf:"bytes,1,opt,name=msgBytes,proto3" json:"msgBytes,omitempty"`
	Time                       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Position                   *Position              `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	CustomRadiusOpt            uint32                 `protobuf:"varint,4,opt,name=customRadiusOpt,proto3" json:"customRadiusOpt,omitempty"`
	ClientCanOverrideRadiusOpt bool                   `protobuf:"varint,5,opt,name=clientCanOverrideRadiusOpt,proto3" json:"clientCanOverrideRadiusOpt,omitempty"`
	ClientIdsOpt               []*ClientIdentity      `protobuf:"bytes,6,rep,name=clientIdsOpt,proto3" json:"clientIdsOpt,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}               `json:"-"`
	XXX_unrecognized           []byte                 `json:"-"`
	XXX_sizecache              int32                  `json:"-"`
}

func (m *RoutedMsg) Reset()         { *m = RoutedMsg{} }
func (m *RoutedMsg) String() string { return proto.CompactTextString(m) }
func (*RoutedMsg) ProtoMessage()    {}
func (*RoutedMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_5813568a872f642d, []int{1}
}

func (m *RoutedMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoutedMsg.Unmarshal(m, b)
}
func (m *RoutedMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoutedMsg.Marshal(b, m, deterministic)
}
func (m *RoutedMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoutedMsg.Merge(m, src)
}
func (m *RoutedMsg) XXX_Size() int {
	return xxx_messageInfo_RoutedMsg.Size(m)
}
func (m *RoutedMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RoutedMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RoutedMsg proto.InternalMessageInfo

func (m *RoutedMsg) GetMsgBytes() []byte {
	if m != nil {
		return m.MsgBytes
	}
	return nil
}

func (m *RoutedMsg) GetTime() *timestamppb.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *RoutedMsg) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *RoutedMsg) GetCustomRadiusOpt() uint32 {
	if m != nil {
		return m.CustomRadiusOpt
	}
	return 0
}

func (m *RoutedMsg) GetClientCanOverrideRadiusOpt() bool {
	if m != nil {
		return m.ClientCanOverrideRadiusOpt
	}
	return false
}

func (m *RoutedMsg) GetClientIdsOpt() []*ClientIdentity {
	if m != nil {
		return m.ClientIdsOpt
	}
	return nil
}

type ClientIdentity struct {
	ClientId             uint32   `protobuf:"varint,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	EntityType           string   `protobuf:"bytes,2,opt,name=entityType,proto3" json:"entityType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientIdentity) Reset()         { *m = ClientIdentity{} }
func (m *ClientIdentity) String() string { return proto.CompactTextString(m) }
func (*ClientIdentity) ProtoMessage()    {}
func (*ClientIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_5813568a872f642d, []int{2}
}

func (m *ClientIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientIdentity.Unmarshal(m, b)
}
func (m *ClientIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientIdentity.Marshal(b, m, deterministic)
}
func (m *ClientIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientIdentity.Merge(m, src)
}
func (m *ClientIdentity) XXX_Size() int {
	return xxx_messageInfo_ClientIdentity.Size(m)
}
func (m *ClientIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_ClientIdentity proto.InternalMessageInfo

func (m *ClientIdentity) GetClientId() uint32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *ClientIdentity) GetEntityType() string {
	if m != nil {
		return m.EntityType
	}
	return ""
}

type AutoPublishAddMsg struct {
	MsgBytes    []byte   `protobuf:"bytes,1,opt,name=msgBytes,proto3" json:"msgBytes,omitempty"`
	MsgType     string   `protobuf:"bytes,2,opt,name=msgType,proto3" json:"msgType,omitempty"`
	Id          string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Description string   `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	EntityTypes []string `protobuf:"bytes,12,rep,name=entityTypes,proto3" json:"entityTypes,omitempty"`
	// the next 4 fields pertain to messages that should be delivered to everyone within a radius at some periodicity
	PositionOpt                *Position              `protobuf:"bytes,4,opt,name=positionOpt,proto3" json:"positionOpt,omitempty"`
	CustomRadiusOpt            uint32                 `protobuf:"varint,5,opt,name=customRadiusOpt,proto3" json:"customRadiusOpt,omitempty"`
	ClientCanOverrideRadiusOpt bool                   `protobuf:"varint,6,opt,name=clientCanOverrideRadiusOpt,proto3" json:"clientCanOverrideRadiusOpt,omitempty"`
	FrequencySecOpt            uint32                 `protobuf:"varint,7,opt,name=frequencySecOpt,proto3" json:"frequencySecOpt,omitempty"`
	StartTime                  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTimeOpt                 *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=endTimeOpt,proto3" json:"endTimeOpt,omitempty"`
	// if LineCrossing is defined then deliver messages to anyone crossing that line
	LineCrossingOpt      *LineCrossing `protobuf:"bytes,10,opt,name=lineCrossingOpt,proto3" json:"lineCrossingOpt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AutoPublishAddMsg) Reset()         { *m = AutoPublishAddMsg{} }
func (m *AutoPublishAddMsg) String() string { return proto.CompactTextString(m) }
func (*AutoPublishAddMsg) ProtoMessage()    {}
func (*AutoPublishAddMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_5813568a872f642d, []int{3}
}

func (m *AutoPublishAddMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoPublishAddMsg.Unmarshal(m, b)
}
func (m *AutoPublishAddMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoPublishAddMsg.Marshal(b, m, deterministic)
}
func (m *AutoPublishAddMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoPublishAddMsg.Merge(m, src)
}
func (m *AutoPublishAddMsg) XXX_Size() int {
	return xxx_messageInfo_AutoPublishAddMsg.Size(m)
}
func (m *AutoPublishAddMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoPublishAddMsg.DiscardUnknown(m)
}

var xxx_messageInfo_AutoPublishAddMsg proto.InternalMessageInfo

func (m *AutoPublishAddMsg) GetMsgBytes() []byte {
	if m != nil {
		return m.MsgBytes
	}
	return nil
}

func (m *AutoPublishAddMsg) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *AutoPublishAddMsg) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AutoPublishAddMsg) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AutoPublishAddMsg) GetEntityTypes() []string {
	if m != nil {
		return m.EntityTypes
	}
	return nil
}

func (m *AutoPublishAddMsg) GetPositionOpt() *Position {
	if m != nil {
		return m.PositionOpt
	}
	return nil
}

func (m *AutoPublishAddMsg) GetCustomRadiusOpt() uint32 {
	if m != nil {
		return m.CustomRadiusOpt
	}
	return 0
}

func (m *AutoPublishAddMsg) GetClientCanOverrideRadiusOpt() bool {
	if m != nil {
		return m.ClientCanOverrideRadiusOpt
	}
	return false
}

func (m *AutoPublishAddMsg) GetFrequencySecOpt() uint32 {
	if m != nil {
		return m.FrequencySecOpt
	}
	return 0
}

func (m *AutoPublishAddMsg) GetStartTime() *timestamppb.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *AutoPublishAddMsg) GetEndTimeOpt() *timestamppb.Timestamp {
	if m != nil {
		return m.EndTimeOpt
	}
	return nil
}

func (m *AutoPublishAddMsg) GetLineCrossingOpt() *LineCrossing {
	if m != nil {
		return m.LineCrossingOpt
	}
	return nil
}

type LineCrossing struct {
	Endpoint1            *Position              `protobuf:"bytes,1,opt,name=endpoint1,proto3" json:"endpoint1,omitempty"`
	Endpoint2            *Position              `protobuf:"bytes,2,opt,name=endpoint2,proto3" json:"endpoint2,omitempty"`
	RoadIdentifier       string                 `protobuf:"bytes,3,opt,name=roadIdentifier,proto3" json:"roadIdentifier,omitempty"`
	Direction            LineCrossing_Direction `protobuf:"varint,4,opt,name=direction,proto3,enum=routedmsgpb.LineCrossing_Direction" json:"direction,omitempty"`
	DistanceOpt          uint32                 `protobuf:"varint,5,opt,name=distanceOpt,proto3" json:"distanceOpt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *LineCrossing) Reset()         { *m = LineCrossing{} }
func (m *LineCrossing) String() string { return proto.CompactTextString(m) }
func (*LineCrossing) ProtoMessage()    {}
func (*LineCrossing) Descriptor() ([]byte, []int) {
	return fileDescriptor_5813568a872f642d, []int{4}
}

func (m *LineCrossing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineCrossing.Unmarshal(m, b)
}
func (m *LineCrossing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineCrossing.Marshal(b, m, deterministic)
}
func (m *LineCrossing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineCrossing.Merge(m, src)
}
func (m *LineCrossing) XXX_Size() int {
	return xxx_messageInfo_LineCrossing.Size(m)
}
func (m *LineCrossing) XXX_DiscardUnknown() {
	xxx_messageInfo_LineCrossing.DiscardUnknown(m)
}

var xxx_messageInfo_LineCrossing proto.InternalMessageInfo

func (m *LineCrossing) GetEndpoint1() *Position {
	if m != nil {
		return m.Endpoint1
	}
	return nil
}

func (m *LineCrossing) GetEndpoint2() *Position {
	if m != nil {
		return m.Endpoint2
	}
	return nil
}

func (m *LineCrossing) GetRoadIdentifier() string {
	if m != nil {
		return m.RoadIdentifier
	}
	return ""
}

func (m *LineCrossing) GetDirection() LineCrossing_Direction {
	if m != nil {
		return m.Direction
	}
	return LineCrossing_Undefined
}

func (m *LineCrossing) GetDistanceOpt() uint32 {
	if m != nil {
		return m.DistanceOpt
	}
	return 0
}

// this is the message a client should publish to remove an Autopublished Message that it added
// the reason this is a Protobuf message at all (given that it has one field) is in case we need to expand it in the future, this gives us flexibility
type AutoPublishDeleteMsg struct {
	MsgType              string   `protobuf:"bytes,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoPublishDeleteMsg) Reset()         { *m = AutoPublishDeleteMsg{} }
func (m *AutoPublishDeleteMsg) String() string { return proto.CompactTextString(m) }
func (*AutoPublishDeleteMsg) ProtoMessage()    {}
func (*AutoPublishDeleteMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_5813568a872f642d, []int{5}
}

func (m *AutoPublishDeleteMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoPublishDeleteMsg.Unmarshal(m, b)
}
func (m *AutoPublishDeleteMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoPublishDeleteMsg.Marshal(b, m, deterministic)
}
func (m *AutoPublishDeleteMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoPublishDeleteMsg.Merge(m, src)
}
func (m *AutoPublishDeleteMsg) XXX_Size() int {
	return xxx_messageInfo_AutoPublishDeleteMsg.Size(m)
}
func (m *AutoPublishDeleteMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoPublishDeleteMsg.DiscardUnknown(m)
}

var xxx_messageInfo_AutoPublishDeleteMsg proto.InternalMessageInfo

func (m *AutoPublishDeleteMsg) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *AutoPublishDeleteMsg) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// acknowledgment for the AutoPublishAddMsg
type AutoPublishAddAck struct {
	MsgType              string   `protobuf:"bytes,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	MsgDescription       string   `protobuf:"bytes,5,opt,name=msgDescription,proto3" json:"msgDescription,omitempty"`
	Success              bool     `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	FailMsg              string   `protobuf:"bytes,4,opt,name=failMsg,proto3" json:"failMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoPublishAddAck) Reset()         { *m = AutoPublishAddAck{} }
func (m *AutoPublishAddAck) String() string { return proto.CompactTextString(m) }
func (*AutoPublishAddAck) ProtoMessage()    {}
func (*AutoPublishAddAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_5813568a872f642d, []int{6}
}

func (m *AutoPublishAddAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoPublishAddAck.Unmarshal(m, b)
}
func (m *AutoPublishAddAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoPublishAddAck.Marshal(b, m, deterministic)
}
func (m *AutoPublishAddAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoPublishAddAck.Merge(m, src)
}
func (m *AutoPublishAddAck) XXX_Size() int {
	return xxx_messageInfo_AutoPublishAddAck.Size(m)
}
func (m *AutoPublishAddAck) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoPublishAddAck.DiscardUnknown(m)
}

var xxx_messageInfo_AutoPublishAddAck proto.InternalMessageInfo

func (m *AutoPublishAddAck) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *AutoPublishAddAck) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AutoPublishAddAck) GetMsgDescription() string {
	if m != nil {
		return m.MsgDescription
	}
	return ""
}

func (m *AutoPublishAddAck) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AutoPublishAddAck) GetFailMsg() string {
	if m != nil {
		return m.FailMsg
	}
	return ""
}

// acknowledgment for the AutoPublishDeleteMsg
type AutoPublishDeleteAck struct {
	MsgType              string   `protobuf:"bytes,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	MsgDescription       string   `protobuf:"bytes,5,opt,name=msgDescription,proto3" json:"msgDescription,omitempty"`
	Success              bool     `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	FailMsg              string   `protobuf:"bytes,4,opt,name=failMsg,proto3" json:"failMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoPublishDeleteAck) Reset()         { *m = AutoPublishDeleteAck{} }
func (m *AutoPublishDeleteAck) String() string { return proto.CompactTextString(m) }
func (*AutoPublishDeleteAck) ProtoMessage()    {}
func (*AutoPublishDeleteAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_5813568a872f642d, []int{7}
}

func (m *AutoPublishDeleteAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoPublishDeleteAck.Unmarshal(m, b)
}
func (m *AutoPublishDeleteAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoPublishDeleteAck.Marshal(b, m, deterministic)
}
func (m *AutoPublishDeleteAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoPublishDeleteAck.Merge(m, src)
}
func (m *AutoPublishDeleteAck) XXX_Size() int {
	return xxx_messageInfo_AutoPublishDeleteAck.Size(m)
}
func (m *AutoPublishDeleteAck) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoPublishDeleteAck.DiscardUnknown(m)
}

var xxx_messageInfo_AutoPublishDeleteAck proto.InternalMessageInfo

func (m *AutoPublishDeleteAck) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *AutoPublishDeleteAck) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AutoPublishDeleteAck) GetMsgDescription() string {
	if m != nil {
		return m.MsgDescription
	}
	return ""
}

func (m *AutoPublishDeleteAck) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AutoPublishDeleteAck) GetFailMsg() string {
	if m != nil {
		return m.FailMsg
	}
	return ""
}

// acknowledgment for the request to delete all messages for the client (which has no associated Protobuf)
type AutoPublishDeleteAllAck struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	FailMsg              string   `protobuf:"bytes,2,opt,name=failMsg,proto3" json:"failMsg,omitempty"`
	Ids                  []string `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoPublishDeleteAllAck) Reset()         { *m = AutoPublishDeleteAllAck{} }
func (m *AutoPublishDeleteAllAck) String() string { return proto.CompactTextString(m) }
func (*AutoPublishDeleteAllAck) ProtoMessage()    {}
func (*AutoPublishDeleteAllAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_5813568a872f642d, []int{8}
}

func (m *AutoPublishDeleteAllAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoPublishDeleteAllAck.Unmarshal(m, b)
}
func (m *AutoPublishDeleteAllAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoPublishDeleteAllAck.Marshal(b, m, deterministic)
}
func (m *AutoPublishDeleteAllAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoPublishDeleteAllAck.Merge(m, src)
}
func (m *AutoPublishDeleteAllAck) XXX_Size() int {
	return xxx_messageInfo_AutoPublishDeleteAllAck.Size(m)
}
func (m *AutoPublishDeleteAllAck) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoPublishDeleteAllAck.DiscardUnknown(m)
}

var xxx_messageInfo_AutoPublishDeleteAllAck proto.InternalMessageInfo

func (m *AutoPublishDeleteAllAck) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AutoPublishDeleteAllAck) GetFailMsg() string {
	if m != nil {
		return m.FailMsg
	}
	return ""
}

func (m *AutoPublishDeleteAllAck) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

// response to client that a message started (applies both to messages that were scheduled and to messages that were started immediately)
type AutoPublishStarted struct {
	MsgType              string   `protobuf:"bytes,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	MsgDescription       string   `protobuf:"bytes,3,opt,name=msgDescription,proto3" json:"msgDescription,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoPublishStarted) Reset()         { *m = AutoPublishStarted{} }
func (m *AutoPublishStarted) String() string { return proto.CompactTextString(m) }
func (*AutoPublishStarted) ProtoMessage()    {}
func (*AutoPublishStarted) Descriptor() ([]byte, []int) {
	return fileDescriptor_5813568a872f642d, []int{9}
}

func (m *AutoPublishStarted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoPublishStarted.Unmarshal(m, b)
}
func (m *AutoPublishStarted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoPublishStarted.Marshal(b, m, deterministic)
}
func (m *AutoPublishStarted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoPublishStarted.Merge(m, src)
}
func (m *AutoPublishStarted) XXX_Size() int {
	return xxx_messageInfo_AutoPublishStarted.Size(m)
}
func (m *AutoPublishStarted) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoPublishStarted.DiscardUnknown(m)
}

var xxx_messageInfo_AutoPublishStarted proto.InternalMessageInfo

func (m *AutoPublishStarted) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *AutoPublishStarted) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AutoPublishStarted) GetMsgDescription() string {
	if m != nil {
		return m.MsgDescription
	}
	return ""
}

// response to client that a message stopped (applies both to messages that expired and to messages that were stopped immediately)
type AutoPublishStopped struct {
	MsgType              string   `protobuf:"bytes,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	MsgDescription       string   `protobuf:"bytes,3,opt,name=msgDescription,proto3" json:"msgDescription,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoPublishStopped) Reset()         { *m = AutoPublishStopped{} }
func (m *AutoPublishStopped) String() string { return proto.CompactTextString(m) }
func (*AutoPublishStopped) ProtoMessage()    {}
func (*AutoPublishStopped) Descriptor() ([]byte, []int) {
	return fileDescriptor_5813568a872f642d, []int{10}
}

func (m *AutoPublishStopped) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoPublishStopped.Unmarshal(m, b)
}
func (m *AutoPublishStopped) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoPublishStopped.Marshal(b, m, deterministic)
}
func (m *AutoPublishStopped) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoPublishStopped.Merge(m, src)
}
func (m *AutoPublishStopped) XXX_Size() int {
	return xxx_messageInfo_AutoPublishStopped.Size(m)
}
func (m *AutoPublishStopped) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoPublishStopped.DiscardUnknown(m)
}

var xxx_messageInfo_AutoPublishStopped proto.InternalMessageInfo

func (m *AutoPublishStopped) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *AutoPublishStopped) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AutoPublishStopped) GetMsgDescription() string {
	if m != nil {
		return m.MsgDescription
	}
	return ""
}

func init() {
	proto.RegisterEnum("routedmsgpb.LineCrossing_Direction", LineCrossing_Direction_name, LineCrossing_Direction_value)
	proto.RegisterType((*Position)(nil), "routedmsgpb.Position")
	proto.RegisterType((*RoutedMsg)(nil), "routedmsgpb.RoutedMsg")
	proto.RegisterType((*ClientIdentity)(nil), "routedmsgpb.ClientIdentity")
	proto.RegisterType((*AutoPublishAddMsg)(nil), "routedmsgpb.AutoPublishAddMsg")
	proto.RegisterType((*LineCrossing)(nil), "routedmsgpb.LineCrossing")
	proto.RegisterType((*AutoPublishDeleteMsg)(nil), "routedmsgpb.AutoPublishDeleteMsg")
	proto.RegisterType((*AutoPublishAddAck)(nil), "routedmsgpb.AutoPublishAddAck")
	proto.RegisterType((*AutoPublishDeleteAck)(nil), "routedmsgpb.AutoPublishDeleteAck")
	proto.RegisterType((*AutoPublishDeleteAllAck)(nil), "routedmsgpb.AutoPublishDeleteAllAck")
	proto.RegisterType((*AutoPublishStarted)(nil), "routedmsgpb.AutoPublishStarted")
	proto.RegisterType((*AutoPublishStopped)(nil), "routedmsgpb.AutoPublishStopped")
}

func init() { proto.RegisterFile("routed_msg.proto", fileDescriptor_5813568a872f642d) }

var fileDescriptor_5813568a872f642d = []byte{
	// 722 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xc5, 0xce, 0xa3, 0xf1, 0x4d, 0x9a, 0x86, 0x11, 0x88, 0x10, 0x10, 0x44, 0x46, 0x42, 0x59,
	0xb9, 0x6a, 0xba, 0x00, 0x75, 0x01, 0xe4, 0xc1, 0x02, 0xa9, 0xa5, 0xd5, 0xb4, 0x88, 0x65, 0xe5,
	0x78, 0x26, 0x66, 0x84, 0x5f, 0x78, 0xc6, 0x48, 0xf9, 0x14, 0x24, 0xb6, 0x7c, 0x02, 0x1f, 0xc0,
	0x9f, 0xa1, 0x19, 0xc7, 0xc9, 0x24, 0x4d, 0x08, 0x02, 0x21, 0xb1, 0x1a, 0xcf, 0xbd, 0xe7, 0xdc,
	0x7b, 0xe6, 0x3e, 0x0c, 0xad, 0x34, 0xce, 0x04, 0x25, 0xd7, 0x21, 0xf7, 0x9d, 0x24, 0x8d, 0x45,
	0x8c, 0xea, 0xb9, 0x25, 0xe4, 0x7e, 0x32, 0xe9, 0x3c, 0xf6, 0xe3, 0xd8, 0x0f, 0xe8, 0xa1, 0x72,
	0x4d, 0xb2, 0xe9, 0xa1, 0x60, 0x21, 0xe5, 0xc2, 0x0d, 0x93, 0x1c, 0x6d, 0x8f, 0xa1, 0x76, 0x11,
	0x73, 0x26, 0x58, 0x1c, 0xa1, 0x0e, 0xd4, 0x02, 0x57, 0x30, 0x91, 0x11, 0xda, 0x36, 0xba, 0x46,
	0xaf, 0x82, 0x17, 0x77, 0xf4, 0x10, 0xac, 0x20, 0x8e, 0xfc, 0xdc, 0x69, 0x2a, 0xe7, 0xd2, 0x60,
	0x7f, 0x37, 0xc1, 0xc2, 0x2a, 0xed, 0x19, 0xf7, 0x65, 0x9c, 0x90, 0xfb, 0xc3, 0x99, 0xa0, 0x5c,
	0xc5, 0x69, 0xe0, 0xc5, 0x1d, 0x39, 0x50, 0x96, 0x12, 0x54, 0x88, 0x7a, 0xbf, 0xe3, 0xe4, 0xfa,
	0x9c, 0x42, 0x9f, 0x73, 0x55, 0xe8, 0xc3, 0x0a, 0x87, 0x8e, 0xa0, 0x96, 0xcc, 0xf5, 0xb5, 0x4b,
	0x8a, 0x73, 0xd7, 0xd1, 0x1e, 0xe8, 0x14, 0xe2, 0xf1, 0x02, 0x86, 0x7a, 0x70, 0xe0, 0x65, 0x5c,
	0xc4, 0x21, 0x76, 0x09, 0xcb, 0xf8, 0x79, 0x22, 0xda, 0xe5, 0xae, 0xd1, 0xdb, 0xc7, 0xeb, 0x66,
	0xf4, 0x02, 0x3a, 0x5e, 0xc0, 0x68, 0x24, 0x46, 0x6e, 0x74, 0xfe, 0x99, 0xa6, 0x29, 0x23, 0x74,
	0x49, 0xaa, 0x74, 0x8d, 0x5e, 0x0d, 0xff, 0x02, 0x81, 0x5e, 0x42, 0x23, 0xf7, 0xbe, 0x21, 0x8a,
	0x51, 0xed, 0x96, 0x7a, 0xf5, 0xfe, 0x83, 0x15, 0x81, 0xa3, 0x39, 0x80, 0x46, 0x82, 0x89, 0x19,
	0x5e, 0x21, 0xd8, 0xa7, 0xd0, 0x5c, 0xf5, 0xcb, 0xda, 0x15, 0x08, 0x55, 0xbb, 0x7d, 0xbc, 0xb8,
	0xa3, 0x47, 0x00, 0x39, 0xea, 0x6a, 0x96, 0xe4, 0x15, 0xb4, 0xb0, 0x66, 0xb1, 0xbf, 0x95, 0xe1,
	0xf6, 0x20, 0x13, 0xf1, 0x45, 0x36, 0x09, 0x18, 0xff, 0x30, 0x20, 0x3b, 0xbb, 0xd1, 0x86, 0xbd,
	0x90, 0xfb, 0x5a, 0xb8, 0xe2, 0x8a, 0x9a, 0x60, 0x32, 0xa2, 0x2a, 0x6e, 0x61, 0x93, 0x11, 0xd4,
	0x85, 0x3a, 0xa1, 0xdc, 0x4b, 0x59, 0xa2, 0x5a, 0x51, 0x57, 0x0e, 0xdd, 0x24, 0x11, 0x4b, 0x2d,
	0xbc, 0xdd, 0xe8, 0x96, 0x24, 0x42, 0x33, 0xa1, 0x67, 0x50, 0x2f, 0x9a, 0x54, 0x34, 0x65, 0x6b,
	0x3b, 0x75, 0xe4, 0xa6, 0x8e, 0x56, 0xfe, 0xa4, 0xa3, 0xd5, 0x9d, 0x1d, 0xed, 0xc1, 0xc1, 0x34,
	0xa5, 0x9f, 0x32, 0x1a, 0x79, 0xb3, 0x4b, 0xea, 0x49, 0xd2, 0x5e, 0x9e, 0x69, 0xcd, 0x8c, 0x9e,
	0x83, 0xc5, 0x85, 0x9b, 0x0a, 0x39, 0xb0, 0xed, 0xda, 0xce, 0x69, 0x5e, 0x82, 0xd1, 0x89, 0x6c,
	0x23, 0x91, 0x9f, 0x32, 0xbc, 0xb5, 0x93, 0xaa, 0xa1, 0xd1, 0x08, 0x0e, 0x02, 0x16, 0xd1, 0x51,
	0x1a, 0x73, 0xce, 0x22, 0x5f, 0x06, 0x00, 0x15, 0xe0, 0xfe, 0x4a, 0x19, 0x4f, 0x35, 0x0c, 0x5e,
	0x67, 0xd8, 0x3f, 0x4c, 0x68, 0xe8, 0x08, 0x74, 0x0c, 0x16, 0x8d, 0x48, 0x12, 0xb3, 0x48, 0x1c,
	0xa9, 0x19, 0xd9, 0xda, 0x96, 0x25, 0x4e, 0x27, 0xf5, 0xe7, 0xeb, 0xbc, 0x8b, 0xd4, 0x47, 0x4f,
	0xa1, 0x99, 0xc6, 0x2e, 0xc9, 0xc7, 0x7d, 0xca, 0x68, 0x3a, 0x1f, 0xb1, 0x35, 0x2b, 0x1a, 0x80,
	0x45, 0x58, 0x4a, 0x3d, 0x35, 0x6c, 0x72, 0x50, 0x9a, 0xfd, 0x27, 0x5b, 0x5f, 0xe8, 0x8c, 0x0b,
	0x28, 0x5e, 0xb2, 0xd4, 0xc4, 0x32, 0x2e, 0xdc, 0xc8, 0xa3, 0xcb, 0x81, 0xd1, 0x4d, 0xf6, 0x09,
	0x58, 0x0b, 0x26, 0xda, 0x07, 0xeb, 0x5d, 0x44, 0xe8, 0x94, 0x45, 0x94, 0xb4, 0x6e, 0xa1, 0x2a,
	0x98, 0x6f, 0x87, 0x2d, 0x43, 0x9e, 0xaf, 0x87, 0x2d, 0x53, 0x9e, 0x97, 0xc3, 0x56, 0x49, 0x9e,
	0xef, 0x87, 0xad, 0xb2, 0xfd, 0x0a, 0xee, 0x68, 0xab, 0x36, 0xa6, 0x01, 0x15, 0x54, 0x6e, 0x9b,
	0xb6, 0x51, 0xc6, 0xa6, 0x8d, 0x32, 0x8b, 0x8d, 0xb2, 0xbf, 0x18, 0xeb, 0xdb, 0x3a, 0xf0, 0x3e,
	0xfe, 0x3e, 0x5f, 0x96, 0x32, 0xe4, 0xfe, 0x58, 0x5b, 0xca, 0x4a, 0x5e, 0xca, 0x55, 0xab, 0x8c,
	0xc8, 0x33, 0xcf, 0xa3, 0x9c, 0xab, 0x5a, 0xd7, 0x70, 0x71, 0x95, 0x9e, 0xa9, 0xcb, 0x82, 0x33,
	0xee, 0xab, 0x12, 0x5b, 0xb8, 0xb8, 0xda, 0x5f, 0x8d, 0x0d, 0xcf, 0xfb, 0x7f, 0xe4, 0x5d, 0xc3,
	0xbd, 0x9b, 0xea, 0x82, 0x60, 0x2e, 0xb0, 0x08, 0x67, 0x6c, 0x0d, 0x67, 0xae, 0x84, 0x43, 0x2d,
	0x28, 0x31, 0x22, 0xd3, 0xcb, 0x3f, 0x96, 0xfc, 0xb4, 0xa7, 0x80, 0xb4, 0x04, 0x97, 0x72, 0x75,
	0x29, 0xf9, 0xab, 0xc7, 0x97, 0x36, 0x3d, 0xfe, 0x46, 0x9e, 0x38, 0x49, 0xfe, 0x45, 0x9e, 0x49,
	0x55, 0xfd, 0x56, 0x8e, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x29, 0x68, 0x7a, 0x2e, 0x08,
	0x00, 0x00,
}
